### ISSUE TITLE
Will disappear if camera within the box. 

### ISSUE THREAD

**Issue by pgruenbacher** [Mr-Slurpy/Screen-Space-Decals#1]
http://martindevans.me/game-development/2015/02/27/Drawing-Stuff-On-Other-Stuff-With-Deferred-Screenspace-Decals/

This blog post covers that sort of issue.

**Comment by Mr-Slurpy** [comment]
Unfortunately I can't use the method described in the blog exactly but it gave me the right idea. By disabling depth testing and doing front cull the decal will always render. I'll push a fix soon.

**Comment by Mr-Slurpy** [comment]
Fixed by 10c83ec4be699b56323c003527d31249b5b213eb.
