### ISSUE TITLE
where is the exemple scene?

### ISSUE THREAD

**Issue by aztecsensei** [Mr-Slurpy/Screen-Space-Decals#3]
hello! i  was trying the plugin but i coudnt figure out how it works, where is the alpha channel option ?
and it looks that the plugin incluyed an exemple scene but its not there anymore?what happened?
>_>

**Comment by Mr-Slurpy** [comment]
You have to pull the repo using git to get the example scene. The scene is excluded if you try to download a zip file of it (this is why godot does not download it when gotten from the asset library). Also, the alpha channel was a bug and is in the latest version. You can download the asset from github or just wait for the asset library to update.

**Comment by aztecsensei** [comment]
so that was the problem,mmm...
but why excluded something very important from the normal download? <_<
anyway,thank you for your answer,most devs just upload their stuff and never see them again.
now we have to wait,hopefully it wont take longer.
:(
 thx

**Comment by Mr-Slurpy** [comment]
Closing since the asset library has finally updated.
