### ISSUE TITLE
Not working with Godot 3.1

### ISSUE THREAD

**Issue by henriquelalves** [Mr-Slurpy/Screen-Space-Decals#4]
The addon doesn't work with Godot 3.1 for some reason; the Shader doesn't throw any errors, but the decal texture is not rendered, no matter if the mesh intersects with the one you want to render it to.

**Comment by Mr-Slurpy** [comment]
This is due an engine bug: https://github.com/godotengine/godot/issues/27438. I'll leave this open until it's fixed. In the meantime, it seems beta 2 works fine so if you need this plugin you can use that.

**Comment by Mr-Slurpy** [comment]
This has been fixed in master. Should be in available in the next patch.
